# **Data Understanding**

**Import required Libraries**

In [4]:
import pandas as pd

**Load the dataset**

In [5]:
df = pd.read_csv("retail_store_sales.csv")

**Check the shape**

In [6]:
df.shape

(12575, 11)

**View the first 5 records**

In [7]:
df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

**Check column names**

In [8]:
for col in df.columns:
    print(col)

Transaction ID
Customer ID
Category
Item
Price Per Unit
Quantity
Total Spent
Payment Method
Location
Transaction Date
Discount Applied

**Check data types**

In [9]:
df.dtypes

Transaction ID       object
Customer ID          object
Category             object
Item                 object
Price Per Unit      float64
Quantity            float64
Total Spent         float64
Payment Method       object
Location             object
Transaction Date     object
Discount Applied     object
dtype: object

**Check missing values**

In [10]:
df.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

**Check duplicate records**

In [11]:
df.duplicated().sum()

np.int64(0)

**Check inconsistent values**

In [12]:
for col in ["Category", "Payment Method", "Location", "Discount Applied"]:
    print("\n", col)
    print(df[col].value_counts(dropna=False))

 Category
Category
Electric household essentials         1591
Furniture                             1591
Food                                  1588
Milk Products                         1584
Butchers                              1568
Beverages                             1567
Computers and electric accessories    1558
Patisserie                            1528
Name: count, dtype: int64

 Payment Method
Payment Method
Cash              4310
Digital Wallet    4144
Credit Card       4121
Name: count, dtype: int64

 Location
Location
Online      6354
In-store    6221
Name: count, dtype: int64

 Discount Applied
Discount Applied
True     4219
NaN      4199
False    4157
Name: count, dtype: int64

**Check the important numeric relationship**

In [13]:
df[["Price Per Unit", "Quantity", "Total Spent"]].describe()

       Price Per Unit      Quantity   Total Spent
count    11966.000000  11971.000000  11971.000000
mean        23.365912      5.536380    129.652577
std         10.743519      2.857883     94.750697
min          5.000000      1.000000      5.000000
25%         14.000000      3.000000     51.000000
50%         23.000000      6.000000    108.500000
75%         33.500000      8.000000    192.000000
max         41.000000     10.000000    410.000000

In [14]:
df[df["Total Spent"].isnull() &
   df["Price Per Unit"].notnull() &
   df["Quantity"].notnull()].head(10)

Empty DataFrame
Columns: [Transaction ID, Customer ID, Category, Item, Price Per Unit, Quantity, Total Spent, Payment Method, Location, Transaction Date, Discount Applied]
Index: []

In [15]:
df[df["Quantity"].isnull() &
   df["Price Per Unit"].notnull() &
   df["Total Spent"].notnull()].head(10)

Empty DataFrame
Columns: [Transaction ID, Customer ID, Category, Item, Price Per Unit, Quantity, Total Spent, Payment Method, Location, Transaction Date, Discount Applied]
Index: []

**Analyze each missing column**

In [16]:
missing_summary = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().sum() / len(df) * 100).round(2)
})

missing_summary

                  Missing_Count  Missing_Percentage
Transaction ID                0                0.00
Customer ID                   0                0.00
Category                      0                0.00
Item                       1213                9.65
Price Per Unit              609                4.84
Quantity                    604                4.80
Total Spent                 604                4.80
Payment Method                0                0.00
Location                      0                0.00
Transaction Date              0                0.00
Discount Applied           4199               33.39

In [17]:
df[df["Item"].isnull()].head(10)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
5,TXN_7482416,CUST_09,Patisserie,NaN,NaN,10.0,200.0,Credit Card,Online,2023-11-30,NaN
7,TXN_1372952,CUST_21,Furniture,NaN,33.5,NaN,NaN,Digital Wallet,In-store,2024-04-02,True
11,TXN_5422631,CUST_09,Milk Products,NaN,NaN,8.0,52.0,Digital Wallet,In-store,2025-01-12,True
15,TXN_1809665,CUST_14,Beverages,NaN,24.5,NaN,NaN,Credit Card,In-store,2022-05-11,NaN
17,TXN_9634894,CUST_15,Milk Products,NaN,NaN,10.0,275.0,Digital Wallet,Online,2022-04-17,NaN
19,TXN_4206593,CUST_01,Furniture,NaN,35.0,NaN,NaN,Digital Wallet,Online,2025-01-13,False
21,TXN_8685338,CUST_15,Milk Products,NaN,NaN,3.0,105.0,Credit Card,In-store,2023-10-29,NaN
25,TXN_3481599,CUST_05,Furniture,NaN,39.5,NaN,NaN,Cash,Online,2022-09-08,False
32,TXN_1543244,CUST_20,Food,NaN,NaN,8.0,196.0,Credit Card,Online,2024-10-25,True
34,TXN_1621497,CUST_06,Patisserie,NaN,23.0,NaN,NaN,Cash,In-store,2023-02-18,NaN

In [18]:
df[df["Price Per Unit"].isnull()].head(10)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
5,TXN_7482416,CUST_09,Patisserie,NaN,NaN,10.0,200.0,Credit Card,Online,2023-11-30,NaN
11,TXN_5422631,CUST_09,Milk Products,NaN,NaN,8.0,52.0,Digital Wallet,In-store,2025-01-12,True
17,TXN_9634894,CUST_15,Milk Products,NaN,NaN,10.0,275.0,Digital Wallet,Online,2022-04-17,NaN
21,TXN_8685338,CUST_15,Milk Products,NaN,NaN,3.0,105.0,Credit Card,In-store,2023-10-29,NaN
32,TXN_1543244,CUST_20,Food,NaN,NaN,8.0,196.0,Credit Card,Online,2024-10-25,True
127,TXN_4608122,CUST_21,Butchers,NaN,NaN,10.0,275.0,Digital Wallet,Online,2022-10-01,False
159,TXN_3822751,CUST_21,Butchers,NaN,NaN,9.0,126.0,Digital Wallet,In-store,2024-03-04,False
216,TXN_7804271,CUST_22,Patisserie,NaN,NaN,8.0,40.0,Cash,Online,2023-02-10,NaN
247,TXN_3433195,CUST_24,Electric household essentials,NaN,NaN,7.0,150.5,Cash,Online,2023-03-30,NaN
271,TXN_7571093,CUST_17,Milk Products,NaN,NaN,9.0,99.0,Digital Wallet,In-store,2022-11-18,NaN

In [19]:
df[df["Quantity"].isnull()].head(10)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
7,TXN_1372952,CUST_21,Furniture,NaN,33.5,NaN,NaN,Digital Wallet,In-store,2024-04-02,True
15,TXN_1809665,CUST_14,Beverages,NaN,24.5,NaN,NaN,Credit Card,In-store,2022-05-11,NaN
19,TXN_4206593,CUST_01,Furniture,NaN,35.0,NaN,NaN,Digital Wallet,Online,2025-01-13,False
25,TXN_3481599,CUST_05,Furniture,NaN,39.5,NaN,NaN,Cash,Online,2022-09-08,False
34,TXN_1621497,CUST_06,Patisserie,NaN,23.0,NaN,NaN,Cash,In-store,2023-02-18,NaN
83,TXN_4532214,CUST_25,Patisserie,NaN,15.5,NaN,NaN,Credit Card,In-store,2024-03-25,False
112,TXN_5419965,CUST_23,Computers and electric accessories,NaN,20.0,NaN,NaN,Digital Wallet,Online,2024-01-16,False
114,TXN_8210621,CUST_03,Beverages,NaN,39.5,NaN,NaN,Digital Wallet,Online,2024-01-03,False
118,TXN_8586300,CUST_11,Computers and electric accessories,NaN,27.5,NaN,NaN,Credit Card,Online,2022-02-08,False
138,TXN_1154680,CUST_25,Furniture,NaN,35.0,NaN,NaN,Credit Card,Online,2022-12-18,False

In [20]:
df[df["Total Spent"].isnull()].head(10)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
7,TXN_1372952,CUST_21,Furniture,NaN,33.5,NaN,NaN,Digital Wallet,In-store,2024-04-02,True
15,TXN_1809665,CUST_14,Beverages,NaN,24.5,NaN,NaN,Credit Card,In-store,2022-05-11,NaN
19,TXN_4206593,CUST_01,Furniture,NaN,35.0,NaN,NaN,Digital Wallet,Online,2025-01-13,False
25,TXN_3481599,CUST_05,Furniture,NaN,39.5,NaN,NaN,Cash,Online,2022-09-08,False
34,TXN_1621497,CUST_06,Patisserie,NaN,23.0,NaN,NaN,Cash,In-store,2023-02-18,NaN
83,TXN_4532214,CUST_25,Patisserie,NaN,15.5,NaN,NaN,Credit Card,In-store,2024-03-25,False
112,TXN_5419965,CUST_23,Computers and electric accessories,NaN,20.0,NaN,NaN,Digital Wallet,Online,2024-01-16,False
114,TXN_8210621,CUST_03,Beverages,NaN,39.5,NaN,NaN,Digital Wallet,Online,2024-01-03,False
118,TXN_8586300,CUST_11,Computers and electric accessories,NaN,27.5,NaN,NaN,Credit Card,Online,2022-02-08,False
138,TXN_1154680,CUST_25,Furniture,NaN,35.0,NaN,NaN,Credit Card,Online,2022-12-18,False

In [21]:
df[df["Discount Applied"].isnull()].head(10)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
5,TXN_7482416,CUST_09,Patisserie,NaN,NaN,10.0,200.0,Credit Card,Online,2023-11-30,NaN
14,TXN_2490363,CUST_09,Milk Products,Item_16_MILK,27.5,2.0,55.0,Digital Wallet,Online,2022-05-22,NaN
15,TXN_1809665,CUST_14,Beverages,NaN,24.5,NaN,NaN,Credit Card,In-store,2022-05-11,NaN
17,TXN_9634894,CUST_15,Milk Products,NaN,NaN,10.0,275.0,Digital Wallet,Online,2022-04-17,NaN
20,TXN_9939063,CUST_14,Beverages,Item_7_BEV,14.0,9.0,126.0,Digital Wallet,In-store,2024-01-14,NaN
21,TXN_8685338,CUST_15,Milk Products,NaN,NaN,3.0,105.0,Credit Card,In-store,2023-10-29,NaN
22,TXN_6547964,CUST_10,Electric household essentials,Item_4_EHE,9.5,7.0,66.5,Cash,In-store,2022-08-15,NaN
33,TXN_1494700,CUST_12,Electric household essentials,Item_21_EHE,35.0,9.0,315.0,Credit Card,In-store,2024-03-07,NaN
34,TXN_1621497,CUST_06,Patisserie,NaN,23.0,NaN,NaN,Cash,In-store,2023-02-18,NaN

**Check inconsistent categorical values**

In [22]:
for col in ["Category", "Payment Method", "Location", "Discount Applied"]:
    print("\n", col)
    print(df[col].value_counts(dropna=False))

 Category
Category
Electric household essentials         1591
Furniture                             1591
Food                                  1588
Milk Products                         1584
Butchers                              1568
Beverages                             1567
Computers and electric accessories    1558
Patisserie                            1528
Name: count, dtype: int64

 Payment Method
Payment Method
Cash              4310
Digital Wallet    4144
Credit Card       4121
Name: count, dtype: int64

 Location
Location
Online      6354
In-store    6221
Name: count, dtype: int64

 Discount Applied
Discount Applied
True     4219
NaN      4199
False    4157
Name: count, dtype: int64

**Check Transaction Date**

In [23]:
df["Transaction Date"].dtype

dtype('O')

In [24]:
df["Transaction Date"].head()

0    2024-04-08
1    2023-07-23
2    2022-10-05
3    2022-05-07
4    2022-10-02
Name: Transaction Date, dtype: object

In [25]:
df["Transaction Date"] = pd.to_datetime(df["Transaction Date"])

**Check all data types**

In [26]:
df.dtypes

Transaction ID              object
Customer ID                 object
Category                    object
Item                        object
Price Per Unit             float64
Quantity                   float64
Total Spent                float64
Payment Method              object
Location                    object
Transaction Date    datetime64[ns]
Discount Applied            object
dtype: object

**Check whether Transaction ID is unique**

In [27]:
df["Transaction ID"].duplicated().sum()

np.int64(0)

In [28]:
df["Customer ID"].duplicated().sum()

np.int64(12550)

**Check numerical/business-rule problems**

In [29]:
print("Negative Price:", (df["Price Per Unit"] < 0).sum())
print("Zero Price:", (df["Price Per Unit"] == 0).sum())
print("Negative Quantity:", (df["Quantity"] < 0).sum())
print("Zero Quantity:", (df["Quantity"] == 0).sum())
print("Negative Total:", (df["Total Spent"] < 0).sum())
print("Zero Total:", (df["Total Spent"] == 0).sum())

Negative Price: 0
Zero Price: 0
Negative Quantity: 0
Zero Quantity: 0
Negative Total: 0
Zero Total: 0

# **Handle Missing Quantity**

**Create a copy**

In [30]:
clean_df = df.copy()

**Fill missing (Price Per Unit)**

In [31]:
mask = (
    clean_df["Price Per Unit"].isnull() &
    clean_df["Quantity"].notnull() &
    clean_df["Total Spent"].notnull()
)

clean_df.loc[mask, "Price Per Unit"] = (
    clean_df.loc[mask, "Total Spent"] / clean_df.loc[mask, "Quantity"]
)

In [32]:
clean_df["Price Per Unit"].isnull().sum()

np.int64(0)

**Fill missing (Total Spent)**

In [33]:
mask = (
    clean_df["Total Spent"].isnull() &
    clean_df["Price Per Unit"].notnull() &
    clean_df["Quantity"].notnull()
)

clean_df.loc[mask, "Total Spent"] = (
    clean_df.loc[mask, "Price Per Unit"] * clean_df.loc[mask, "Quantity"]
)

In [34]:
clean_df["Total Spent"].isnull().sum()

np.int64(604)

**Fill missing (Quantity)**

In [35]:
mask = (
    clean_df["Quantity"].isnull() &
    clean_df["Price Per Unit"].notnull() &
    clean_df["Total Spent"].notnull()
)

clean_df.loc[mask, "Quantity"] = (
    clean_df.loc[mask, "Total Spent"] / clean_df.loc[mask, "Price Per Unit"]
)

In [36]:
clean_df["Quantity"].isnull().sum()

np.int64(604)

In [37]:
print("Missing Price:", clean_df["Price Per Unit"].isnull().sum())
print("Missing Quantity:", clean_df["Quantity"].isnull().sum())
print("Missing Total:", clean_df["Total Spent"].isnull().sum())

Missing Price: 0
Missing Quantity: 604
Missing Total: 604

In [38]:
clean_df[
    clean_df["Quantity"].isnull() &
    clean_df["Total Spent"].isnull()
].head(10)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
7,TXN_1372952,CUST_21,Furniture,NaN,33.5,NaN,NaN,Digital Wallet,In-store,2024-04-02,True
15,TXN_1809665,CUST_14,Beverages,NaN,24.5,NaN,NaN,Credit Card,In-store,2022-05-11,NaN
19,TXN_4206593,CUST_01,Furniture,NaN,35.0,NaN,NaN,Digital Wallet,Online,2025-01-13,False
25,TXN_3481599,CUST_05,Furniture,NaN,39.5,NaN,NaN,Cash,Online,2022-09-08,False
34,TXN_1621497,CUST_06,Patisserie,NaN,23.0,NaN,NaN,Cash,In-store,2023-02-18,NaN
83,TXN_4532214,CUST_25,Patisserie,NaN,15.5,NaN,NaN,Credit Card,In-store,2024-03-25,False
112,TXN_5419965,CUST_23,Computers and electric accessories,NaN,20.0,NaN,NaN,Digital Wallet,Online,2024-01-16,False
114,TXN_8210621,CUST_03,Beverages,NaN,39.5,NaN,NaN,Digital Wallet,Online,2024-01-03,False
118,TXN_8586300,CUST_11,Computers and electric accessories,NaN,27.5,NaN,NaN,Credit Card,Online,2022-02-08,False
138,TXN_1154680,CUST_25,Furniture,NaN,35.0,NaN,NaN,Credit Card,Online,2022-12-18,False

In [39]:
clean_df[
    clean_df["Quantity"].isnull() &
    clean_df["Total Spent"].isnull()
]["Category"].value_counts()

Category
Patisserie                            87
Computers and electric accessories    81
Food                                  81
Electric household essentials         75
Butchers                              72
Beverages                             71
Milk Products                         71
Furniture                             66
Name: count, dtype: int64

In [40]:
clean_df[
    clean_df["Quantity"].isnull() &
    clean_df["Total Spent"].isnull()
]["Price Per Unit"].describe()

count    604.000000
mean      23.536424
std       10.891040
min        5.000000
25%       14.000000
50%       23.000000
75%       33.500000
max       41.000000
Name: Price Per Unit, dtype: float64

**Check whether Quantity can be reasonably imputed**

In [41]:
clean_df.groupby("Category")["Quantity"].agg(["count", "median", "mean"])

                                    count  median      mean
Category
Beverages                            1496     6.0  5.586898
Butchers                             1496     5.0  5.485294
Computers and electric accessories   1477     6.0  5.600542
Electric household essentials        1516     6.0  5.480871
Food                                 1507     6.0  5.565362
Furniture                            1525     6.0  5.548852
Milk Products                        1513     6.0  5.511566
Patisserie                           1441     6.0  5.512144

**Check the actual quantity distribution**

In [42]:
clean_df["Quantity"].value_counts().sort_index()

Quantity
1.0     1147
2.0     1164
3.0     1224
4.0     1155
5.0     1228
6.0     1220
7.0     1227
8.0     1226
9.0     1148
10.0    1232
Name: count, dtype: int64

**One more important check for (Item)**

In [43]:
clean_df[
    clean_df["Item"].isnull()
][["Category", "Price Per Unit"]].head(20)

                               Category  Price Per Unit
5                            Patisserie            20.0
7                             Furniture            33.5
11                        Milk Products             6.5
15                            Beverages            24.5
17                        Milk Products            27.5
19                            Furniture            35.0
21                        Milk Products            35.0
25                            Furniture            39.5
32                                 Food            24.5
34                           Patisserie            23.0
83                           Patisserie            15.5
112  Computers and electric accessories            20.0
114                           Beverages            39.5
118  Computers and electric accessories            27.5
127                            Butchers            27.5
138                           Furniture            35.0
139                           Furniture            24.5
159                            Butchers            14.0
179                            Butchers            23.0
182                           Beverages             6.5

In [44]:
clean_df.groupby(
    ["Category", "Price Per Unit"]
)["Item"].nunique()

Category    Price Per Unit
Beverages   5.0               1
            6.5               1
            8.0               1
            9.5               1
            11.0              1
                             ..
Patisserie  35.0              1
            36.5              1
            38.0              1
            39.5              1
            41.0              1
Name: Item, Length: 200, dtype: int64

In [45]:
clean_df["Quantity"] = clean_df["Quantity"].fillna(
    clean_df.groupby("Category")["Quantity"].transform("median")
)

clean_df["Quantity"] = clean_df["Quantity"].astype(int)

In [46]:
clean_df["Total Spent"] = clean_df["Total Spent"].fillna(
    clean_df["Price Per Unit"] * clean_df["Quantity"]
)

In [47]:
clean_df.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit         0
Quantity               0
Total Spent            0
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [48]:
item_lookup = (
    clean_df.dropna(subset=["Item"])
    .drop_duplicates(["Category", "Price Per Unit"])
    .set_index(["Category", "Price Per Unit"])["Item"]
)

In [49]:
mask = clean_df["Item"].isnull()

clean_df.loc[mask, "Item"] = [
    item_lookup.get((category, price))
    for category, price in zip(
        clean_df.loc[mask, "Category"],
        clean_df.loc[mask, "Price Per Unit"]
    )
]

In [50]:
clean_df["Item"].isnull().sum()

np.int64(0)

In [51]:
clean_df["Discount Applied"].value_counts(dropna=False)

Discount Applied
True     4219
NaN      4199
False    4157
Name: count, dtype: int64

**Investigate whether Discount Applied can be derived**

In [52]:
clean_df["Calculated Total"] = (
    clean_df["Price Per Unit"] * clean_df["Quantity"]
)

In [53]:
clean_df.groupby("Discount Applied")[
    ["Price Per Unit", "Quantity", "Total Spent", "Calculated Total"]
].mean()

                  Price Per Unit  Quantity  Total Spent  Calculated Total
Discount Applied
False                  23.405942  5.594660   130.641208        130.641208
True                   23.463617  5.549893   130.856957        130.856957

In [54]:
clean_df["Discount Difference"] = (
    clean_df["Calculated Total"] - clean_df["Total Spent"]
)

In [55]:
clean_df.groupby("Discount Applied")["Discount Difference"].describe()

                   count  mean  std  min  25%  50%  75%  max
Discount Applied
False             4157.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
True              4219.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0

**Handle missing Discount Applied**

In [56]:
clean_df["Discount Applied"] = clean_df["Discount Applied"].fillna("Unknown")

In [57]:
clean_df["Discount Applied"].value_counts()

Discount Applied
True       4219
Unknown    4199
False      4157
Name: count, dtype: int64

**Remove our temporary analysis columns**

In [58]:
clean_df.drop(
    columns=["Calculated Total", "Discount Difference"],
    inplace=True
)

**Final missing-value check**

In [59]:
clean_df.isnull().sum()

Transaction ID      0
Customer ID         0
Category            0
Item                0
Price Per Unit      0
Quantity            0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
Discount Applied    0
dtype: int64

In [60]:
clean_df.shape

(12575, 11)

**Check categorical inconsistencies**

In [61]:
for col in ["Category", "Payment Method", "Location", "Discount Applied"]:
    print("\n", col)
    print(clean_df[col].value_counts())

 Category
Category
Electric household essentials         1591
Furniture                             1591
Food                                  1588
Milk Products                         1584
Butchers                              1568
Beverages                             1567
Computers and electric accessories    1558
Patisserie                            1528
Name: count, dtype: int64

 Payment Method
Payment Method
Cash              4310
Digital Wallet    4144
Credit Card       4121
Name: count, dtype: int64

 Location
Location
Online      6354
In-store    6221
Name: count, dtype: int64

 Discount Applied
Discount Applied
True       4219
Unknown    4199
False      4157
Name: count, dtype: int64

In [62]:
for col in ["Category", "Payment Method", "Location"]:
    print(col, clean_df[col].astype(str).str.strip().nunique(),
          clean_df[col].nunique())

Category 8 8
Payment Method 3 3
Location 2 2

**Check data types after cleaning**

In [63]:
clean_df.dtypes

Transaction ID              object
Customer ID                 object
Category                    object
Item                        object
Price Per Unit             float64
Quantity                     int64
Total Spent                float64
Payment Method              object
Location                    object
Transaction Date    datetime64[ns]
Discount Applied            object
dtype: object

**Final duplicate check**

In [64]:
print("Duplicate rows:", clean_df.duplicated().sum())
print("Duplicate Transaction IDs:", clean_df["Transaction ID"].duplicated().sum())

Duplicate rows: 0
Duplicate Transaction IDs: 0

**Final data validation**

In [65]:
clean_df.isnull().sum()

Transaction ID      0
Customer ID         0
Category            0
Item                0
Price Per Unit      0
Quantity            0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
Discount Applied    0
dtype: int64

In [66]:
print("Negative Price:", (clean_df["Price Per Unit"] < 0).sum())
print("Negative Quantity:", (clean_df["Quantity"] < 0).sum())
print("Negative Total:", (clean_df["Total Spent"] < 0).sum())

Negative Price: 0
Negative Quantity: 0
Negative Total: 0

In [67]:
calculated_total = clean_df["Price Per Unit"] * clean_df["Quantity"]

print(
    "Incorrect Total Spent:",
    (clean_df["Total Spent"] != calculated_total).sum()
)

Incorrect Total Spent: 0

**Check final shape**

In [68]:
clean_df.shape

(12575, 11)

**Final preview**

In [69]:
clean_df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9,247.5,Credit Card,Online,2022-05-07,Unknown
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7,87.5,Digital Wallet,Online,2022-10-02,False

In [70]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  object
 1   Customer ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Item              12575 non-null  object
 4   Price Per Unit    12575 non-null  float64
 5   Quantity          12575 non-null  int64
 6   Total Spent       12575 non-null  float64
 7   Payment Method    12575 non-null  object
 8   Location          12575 non-null  object
 9   Transaction Date  12575 non-null  datetime64[ns]
 10  Discount Applied  12575 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(7)
memory usage: 1.1+ MB